# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieListCoreData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieListCoreData
	pod 'ImageLoader'
	pod 'Alamofire', '~> 5.1'
end
